// <auto-generated />
using System;
using Humidity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace humidity_api_minimal.Migrations
{
    [DbContext(typeof(HumidityDb))]
    [Migration("20231210223040_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Humidity.HumidityData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("humidity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sensorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HumidityDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
